name: My Workflow
on: [push]
jobs:
   CI:
      runs-on: ubuntu-latest
      steps:
         - name: Checking some dependencies
           run: pythin --version; pip --version
         - name: Install extra dpednencies
           run: pip install -U numpy
         - uses: actions:checkout@v1
         - name: Build
           run: python main.py
